apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-upload-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-upload
  template:
    metadata:
      labels:
        app: image-upload
    spec:
      containers:
      - name: image-upload-container
        image: gsaiadhinathareddy/django_image_upload:v3  # Replace with the actual image name
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: image-upload
          mountPath: /app/uploads  # Update with the correct mount path in the container
      volumes:
      - name: image-upload
        persistentVolumeClaim:
          claimName: image-pvc
