apiVersion: v1
kind: Service
metadata:
  name: image-upload-service
spec:
  selector:
    app: image-upload
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort  # You can change the service type as needed
